# Generated by Django 4.1.7 on 2023-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('I', 'In Progress'), ('F', 'Finished')], default='I', max_length=1),
        ),
    ]
